version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
    environment:
      - USER_SERVICE_URL=http://user-service:4001
      - PRODUCT_SERVICE_URL=http://product-service:4002

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - MONGODB_URI=mongodb://mongo:27017/user-service

  product-service:
    build: ./product-service
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - MONGODB_URI=mongodb://mongo:27017/product-service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
